import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { emptyData } from './data'
import { loadData, saveData } from './db'
import { allocationByType, balanceOf, rateFor, removeAccount, totalFor } from './ledger'
import { accountTypes, colors, supportedCurrencies, uid, type Account, type AccountKind, type AccountType, type AppData, type Category, type EntryType, type Rate, type Transaction } from './types'

type Page = 'assets' | 'accounts' | 'bills' | 'settings'
type ModalState = null | { kind: 'account'; account?: Account } | { kind: 'entry'; entry?: Transaction }
const today = () => new Date().toISOString().slice(0, 10)
const money = (value: number, currency = 'CNY') => {
  try { return new Intl.NumberFormat('zh-CN', { style: 'currency', currency, maximumFractionDigits: ['BTC', 'ETH'].includes(currency) ? 6 : 2 }).format(value || 0) }
  catch { return `${new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 6 }).format(value || 0)} ${currency}` }
}
const displayDate = (date: string) => new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric' }).format(new Date(`${date}T12:00:00`))
const accountName = (accounts: Account[], id?: string) => accounts.find(a => a.id === id)?.name ?? '已删除账户'

function Modal({ children, onClose, title }: { children: ReactNode; onClose: () => void; title: string }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e => e.stopPropagation()}>
    <header className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭">×</button></header>{children}
  </section></div>
}

function AssetsPage({ data, openEntry }: { data: AppData; openEntry: () => void }) {
  const assets = totalFor(data, 'asset'), liabilities = totalFor(data, 'liability'), net = assets - liabilities
  const distribution = allocationByType(data), max = distribution.reduce((sum, item) => sum + item.value, 0)
  let cursor = 0
  const wheel = distribution.length ? `conic-gradient(${distribution.map((item, i) => { const start = cursor; cursor += max ? item.value / max * 360 : 0; return `${colors[i % colors.length]} ${start}deg ${cursor}deg` }).join(', ')})` : '#e9edea'
  const missing = data.accounts.filter(a => !a.archived && rateFor(data, a.currency) === undefined)
  const accounts = [...data.accounts].filter(a => !a.archived).sort((a, b) => a.sortOrder - b.sortOrder)
  return <main className="page assets-page">
    <header className="page-head"><div><p className="eyebrow">我的资产</p><h1>资产总览</h1></div><button className="record-button" onClick={openEntry}><span>＋</span> 记一笔</button></header>
    <section className="net-card"><p>净资产 <span className="quiet">{data.settings.baseCurrency}</span></p><strong>{money(net, data.settings.baseCurrency)}</strong><div className="net-details"><span>资产 <b>{money(assets, data.settings.baseCurrency)}</b></span><i/><span>负债 <b>{money(liabilities, data.settings.baseCurrency)}</b></span></div></section>
    {missing.length > 0 && <div className="notice">{missing.map(a => a.currency.toUpperCase()).filter((x, i, arr) => arr.indexOf(x) === i).join('、')} 尚未设置汇率，未计入总额</div>}
    <section className="section-title"><div><h2>资产分布</h2><p>按账户类型</p></div><span className="muted">仅资产账户</span></section>
    {distribution.length ? <section className="distribution-card"><div className="donut" style={{ background: wheel }}><div><b>{money(assets, data.settings.baseCurrency)}</b><span>可换算资产</span></div></div><div className="legend">{distribution.map((item, index) => <div key={item.type}><i style={{ background: colors[index % colors.length] }}/><span>{accountTypes[item.type as AccountType].label}</span><b>{max ? Math.round(item.value / max * 100) : 0}%</b></div>)}</div></section> : <div className="empty-card"><span>◇</span><b>从第一个账户开始</b><p>添加账户后，在这里查看资产分布。</p></div>}
    <section className="section-title accounts-title"><div><h2>账户</h2><p>{accounts.length} 个账户</p></div></section>
    <section className="account-list">{accounts.slice(0, 6).map(account => <AccountRow key={account.id} account={account} data={data}/>)}</section>
  </main>
}

function AccountRow({ account, data, controls, onEdit }: { account: Account; data: AppData; controls?: ReactNode; onEdit?: () => void }) {
  const value = balanceOf(account, data.transactions), converted = rateFor(data, account.currency)
  return <article className="account-row" onClick={onEdit}><span className="account-icon" style={{ color: account.color, background: `${account.color}18` }}>{account.icon || accountTypes[account.type].icon}</span><div className="account-copy"><b>{account.name}</b><small>{accountTypes[account.type].label} · {account.currency.toUpperCase()}</small></div><div className="account-balance"><b>{money(value, account.currency)}</b>{converted === undefined ? <small className="missing">待更新汇率</small> : account.currency.toUpperCase() !== data.settings.baseCurrency.toUpperCase() && <small>≈ {money(value * converted, data.settings.baseCurrency)}</small>}</div>{controls}</article>
}

function AccountsPage({ data, setData, openAccount }: { data: AppData; setData: (fn: (data: AppData) => AppData) => void; openAccount: (account?: Account) => void }) {
  const [dragId, setDragId] = useState<string | null>(null)
  const accounts = [...data.accounts].filter(a => !a.archived).sort((a, b) => a.sortOrder - b.sortOrder)
  const reorder = (from: string, to: string) => {
    if (from === to) return
    setData(current => { const all = [...current.accounts]; const fromIndex = all.findIndex(a => a.id === from), toIndex = all.findIndex(a => a.id === to); const [item] = all.splice(fromIndex, 1); all.splice(toIndex, 0, item); return { ...current, accounts: all.map((a, index) => ({ ...a, sortOrder: index })) } })
  }
  const move = (id: string, delta: number) => { const index = accounts.findIndex(a => a.id === id), other = accounts[index + delta]; if (other) reorder(id, other.id) }
  return <main className="page">
    <header className="page-head"><div><p className="eyebrow">账户管理</p><h1>我的账户</h1></div><button className="round-add" onClick={() => openAccount()}>＋</button></header>
    <p className="helper">长按拖动可调整顺序，点击账户可编辑。</p>
    <section className="account-list sortable-list">{accounts.length ? accounts.map((account, index) => <div key={account.id} draggable onDragStart={() => setDragId(account.id)} onDragOver={e => e.preventDefault()} onDrop={() => { if (dragId) reorder(dragId, account.id); setDragId(null) }}><AccountRow account={account} data={data} onEdit={() => openAccount(account)} controls={<span className="sort-buttons" onClick={e => e.stopPropagation()}><button disabled={index === 0} onClick={() => move(account.id, -1)}>↑</button><button disabled={index === accounts.length - 1} onClick={() => move(account.id, 1)}>↓</button></span>}/></div>) : <div className="empty-card"><span>＋</span><b>还没有账户</b><p>银行卡、投资、海外账户和负债都可以添加。</p><button className="primary-button" onClick={() => openAccount()}>添加第一个账户</button></div>}</section>
  </main>
}

function BillsPage({ data, openEntry, editEntry, removeEntry }: { data: AppData; openEntry: () => void; editEntry: (entry: Transaction) => void; removeEntry: (entry: Transaction) => void }) {
  const [month, setMonth] = useState(today().slice(0, 7)); const [filter, setFilter] = useState(''); const [query, setQuery] = useState('')
  const entries = [...data.transactions].filter(item => item.date.startsWith(month) && (!filter || item.accountId === filter || item.targetAccountId === filter) && (!query || item.note?.toLowerCase().includes(query.toLowerCase()) || (item.categoryId && data.categories.find(c => c.id === item.categoryId)?.name.includes(query)))).sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt))
  return <main className="page">
    <header className="page-head"><div><p className="eyebrow">账单</p><h1>资金流水</h1></div><button className="round-add" onClick={openEntry}>＋</button></header>
    <div className="filters"><input type="month" value={month} onChange={e => setMonth(e.target.value)}/><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">全部账户</option>{data.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select><input className="search" placeholder="搜索备注或分类" value={query} onChange={e => setQuery(e.target.value)}/></div>
    <section className="entry-list">{entries.length ? entries.map(entry => <EntryRow key={entry.id} entry={entry} data={data} onEdit={() => editEntry(entry)} onRemove={() => removeEntry(entry)}/>) : <div className="empty-card"><span>⌁</span><b>这个月还没有记录</b><p>每一笔收支都会自动更新账户余额。</p><button className="primary-button" onClick={openEntry}>记一笔</button></div>}</section>
  </main>
}

function EntryRow({ entry, data, onEdit, onRemove }: { entry: Transaction; data: AppData; onEdit: () => void; onRemove: () => void }) {
  const category = data.categories.find(c => c.id === entry.categoryId)
  const info = entry.type === 'transfer' ? `${accountName(data.accounts, entry.accountId)} → ${accountName(data.accounts, entry.targetAccountId)}` : entry.type === 'adjustment' ? `余额调整 · ${accountName(data.accounts, entry.accountId)}` : `${category?.name ?? (entry.type === 'income' ? '收入' : '支出')} · ${accountName(data.accounts, entry.accountId)}`
  const positive = entry.type === 'income' || entry.type === 'adjustment' && entry.amount >= 0
  const currency = data.accounts.find(a => a.id === entry.accountId)?.currency ?? 'CNY'
  return <article className="entry-row"><span className={`entry-icon ${entry.type}`}>{entry.type === 'transfer' ? '↔' : category?.icon ?? (entry.type === 'income' ? '↑' : entry.type === 'adjustment' ? '≈' : '↓')}</span><div onClick={onEdit}><b>{info}</b><small>{displayDate(entry.date)}{entry.note ? ` · ${entry.note}` : ''}</small></div><div className={`entry-amount ${positive ? 'positive' : ''}`} onClick={onEdit}><b>{entry.type === 'transfer' ? `${money(entry.amount, currency)} →` : `${positive ? '+' : '−'}${money(Math.abs(entry.amount), currency)}`}</b></div><button className="delete-entry" aria-label="删除流水" onClick={onRemove}>×</button></article>
}

function SettingsPage({ data, setData, updateRates, importData }: { data: AppData; setData: (fn: (data: AppData) => AppData) => void; updateRates: () => void; importData: (file: File) => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const [catName, setCatName] = useState(''); const [catDirection, setCatDirection] = useState<'income' | 'expense'>('expense')
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `jingzi-backup-${today()}.json`; link.click(); URL.revokeObjectURL(link.href) }
  const addCategory = () => { if (!catName.trim()) return; setData(current => ({ ...current, categories: [...current.categories, { id: uid(), name: catName.trim(), direction: catDirection, color: colors[current.categories.length % colors.length], icon: catDirection === 'income' ? '↑' : '•', sortOrder: current.categories.length, active: true }] })); setCatName('') }
  return <main className="page settings-page">
    <header className="page-head"><div><p className="eyebrow">设置</p><h1>本地与汇率</h1></div></header>
    <section className="setting-section"><div className="setting-heading"><div><h2>主币种</h2><p>资产总览会自动换算为此币种</p></div></div><select className="base-currency" value={data.settings.baseCurrency} onChange={e => setData(current => ({ ...current, settings: { ...current.settings, baseCurrency: e.target.value } }))}>{supportedCurrencies.map(([code, label]) => <option key={code} value={code}>{code} · {label}</option>)}</select></section>
    <section className="setting-section"><div className="setting-heading"><div><h2>自动汇率</h2><p>法币、USDT、USDC、BTC 与 ETH 统一自动获取</p></div><button className="outline-button" onClick={updateRates}>↻ 更新汇率</button></div><p className="tiny">{data.settings.lastRateUpdate ? `上次更新：${new Date(data.settings.lastRateUpdate).toLocaleString('zh-CN')}` : '尚未获取汇率。联网后点击更新即可。'}</p><div className="rate-list">{supportedCurrencies.map(([code, label]) => { const rate = rateFor(data, code); return <div key={code} className="rate-row readonly-rate"><div><b>{code}</b><small>{label}</small></div><span>{rate === undefined ? '等待更新' : code === data.settings.baseCurrency ? `1 ${code}` : `≈ ${rate.toLocaleString('zh-CN', { maximumFractionDigits: 6 })} ${data.settings.baseCurrency}`}</span><small>{data.rates[code] || code === 'USD' ? '自动' : '—'}</small></div>})}</div></section>
    <section className="setting-section"><div className="setting-heading"><div><h2>数据备份</h2><p>全部数据仅保存在此设备</p></div></div><div className="backup-actions"><button className="primary-button" onClick={exportData}>导出 JSON 备份</button><button className="outline-button" onClick={() => fileRef.current?.click()}>导入并恢复</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={e => { const file = e.target.files?.[0]; if (file) importData(file); e.currentTarget.value = '' }}/></div></section>
    <section className="setting-section"><div className="setting-heading"><div><h2>分类管理</h2><p>停用后不会出现在新增流水中</p></div></div><div className="category-list">{[...data.categories].sort((a, b) => a.sortOrder - b.sortOrder).map(category => <button key={category.id} className={!category.active ? 'disabled-category' : ''} onClick={() => setData(current => ({ ...current, categories: current.categories.map(c => c.id === category.id ? { ...c, active: !c.active } : c) }))}><i style={{ background: category.color }}>{category.icon}</i>{category.name}<small>{category.direction === 'income' ? '收入' : '支出'} · {category.active ? '已启用' : '已停用'}</small></button>)}</div><div className="inline-form"><input placeholder="新增分类" value={catName} onChange={e => setCatName(e.target.value)}/><select value={catDirection} onChange={e => setCatDirection(e.target.value as 'income' | 'expense')}><option value="expense">支出</option><option value="income">收入</option></select><button onClick={addCategory}>添加</button></div></section>
    <p className="privacy-note">没有登录、没有云同步、没有广告追踪。清除 Safari 网站数据前，请先导出备份。</p>
  </main>
}

function AccountForm({ data, account, onSave, onDelete, onClose }: { data: AppData; account?: Account; onSave: (account: Account) => void; onDelete: (account: Account) => void; onClose: () => void }) {
  const [form, setForm] = useState({ name: account?.name ?? '', kind: account?.kind ?? 'asset' as AccountKind, type: account?.type ?? 'bank' as AccountType, currency: account?.currency ?? 'CNY', openingBalance: String(account?.openingBalance ?? ''), color: account?.color ?? colors[data.accounts.length % colors.length], icon: account?.icon ?? '', note: account?.note ?? '' })
  const save = (e: FormEvent) => { e.preventDefault(); const balance = Number(form.openingBalance || 0); if (!form.name.trim() || !Number.isFinite(balance)) return; onSave({ id: account?.id ?? uid(), name: form.name.trim(), kind: form.kind, type: form.type, currency: form.currency.trim().toUpperCase(), openingBalance: balance, color: form.color, icon: form.icon || accountTypes[form.type].icon, note: form.note, sortOrder: account?.sortOrder ?? data.accounts.length, createdAt: account?.createdAt ?? new Date().toISOString() }) }
  return <Modal title={account ? '编辑账户' : '新增账户'} onClose={onClose}><form className="form-stack" onSubmit={save}><label>账户名称<input autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="如：招商银行储蓄卡"/></label><div className="two-fields"><label>属性<select value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value as AccountKind, type: e.target.value === 'liability' && form.type === 'bank' ? 'credit-card' : form.type })}><option value="asset">资产</option><option value="liability">负债</option></select></label><label>账户类型<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value as AccountType })}>{Object.entries(accountTypes).filter(([key]) => form.kind === 'asset' ? !['credit-card', 'loan'].includes(key) : ['credit-card', 'loan', 'other'].includes(key)).map(([key, type]) => <option key={key} value={key}>{type.label}</option>)}</select></label></div><div className="two-fields"><label>币种<select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}>{supportedCurrencies.map(([code, label]) => <option key={code} value={code}>{code} · {label}</option>)}</select></label><label>期初余额<input inputMode="decimal" value={form.openingBalance} onChange={e => setForm({ ...form, openingBalance: e.target.value })} placeholder="0.00"/></label></div><label>备注（可选）<input value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} placeholder="例如：日常使用"/></label><div className="color-picker"><span>标记色</span>{colors.map(color => <button type="button" key={color} className={form.color === color ? 'selected' : ''} style={{ background: color }} onClick={() => setForm({ ...form, color })}/>)}</div><button className="primary-button form-submit" type="submit">保存账户</button>{account && <button className="danger-button" type="button" onClick={() => onDelete(account)}>删除账户</button>}</form></Modal>
}

function EntryForm({ data, entry, onSave, onClose }: { data: AppData; entry?: Transaction; onSave: (entry: Transaction) => void; onClose: () => void }) {
  const [type, setType] = useState<EntryType>(entry?.type ?? 'expense'); const [accountId, setAccountId] = useState(entry?.accountId ?? data.accounts.find(a => !a.archived)?.id ?? ''); const [targetAccountId, setTargetAccountId] = useState(entry?.targetAccountId ?? ''); const [amount, setAmount] = useState(String(entry?.amount ?? '')); const [targetAmount, setTargetAmount] = useState(String(entry?.targetAmount ?? entry?.amount ?? '')); const [categoryId, setCategoryId] = useState(entry?.categoryId ?? ''); const [date, setDate] = useState(entry?.date ?? today()); const [note, setNote] = useState(entry?.note ?? ''); const [error, setError] = useState('')
  const categories = data.categories.filter(c => c.active && c.direction === (type === 'income' ? 'income' : 'expense'))
  const save = (e: FormEvent) => { e.preventDefault(); const numeric = Number(amount), targetNumeric = Number(targetAmount); if (!accountId || !Number.isFinite(numeric) || numeric === 0) return setError('请选择账户并填写有效金额。'); if (type === 'transfer' && (!targetAccountId || targetAccountId === accountId || !Number.isFinite(targetNumeric) || targetNumeric <= 0)) return setError('请选择不同的转入账户并填写到账金额。'); if ((type === 'income' || type === 'expense') && !categoryId) return setError('请选择分类。'); onSave({ id: entry?.id ?? uid(), type, accountId, targetAccountId: type === 'transfer' ? targetAccountId : undefined, amount: type === 'adjustment' ? numeric : Math.abs(numeric), targetAmount: type === 'transfer' ? Math.abs(targetNumeric) : undefined, categoryId: type === 'income' || type === 'expense' ? categoryId : undefined, date, note: note.trim(), createdAt: entry?.createdAt ?? new Date().toISOString() }) }
  return <Modal title={entry ? '编辑流水' : '记一笔'} onClose={onClose}><form className="form-stack" onSubmit={save}><div className="segmented">{([['expense', '支出'], ['income', '收入'], ['transfer', '转账'], ['adjustment', '校准']] as [EntryType, string][]).map(([value, label]) => <button type="button" className={type === value ? 'active' : ''} key={value} onClick={() => { setType(value); setError(''); }}>{label}</button>)}</div><label>{type === 'transfer' ? '转出账户' : '账户'}<select value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">选择账户</option>{data.accounts.filter(a => !a.archived).map(a => <option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label>{type === 'transfer' && <label>转入账户<select value={targetAccountId} onChange={e => setTargetAccountId(e.target.value)}><option value="">选择账户</option>{data.accounts.filter(a => !a.archived && a.id !== accountId).map(a => <option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label>}<div className={type === 'transfer' ? 'two-fields' : ''}><label>{type === 'adjustment' ? '调整额（可填负数）' : type === 'transfer' ? '转出金额' : '金额'}<input autoFocus inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00"/></label>{type === 'transfer' && <label>到账金额<input inputMode="decimal" value={targetAmount} onChange={e => setTargetAmount(e.target.value)} placeholder="0.00"/></label>}</div>{(type === 'income' || type === 'expense') && <label>分类<select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">选择分类</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>日期<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>备注（可选）<input value={note} onChange={e => setNote(e.target.value)} placeholder="写下这笔记录的说明"/></label>{error && <p className="form-error">{error}</p>}<button className="primary-button form-submit" type="submit">保存记录</button></form></Modal>
}

export default function App() {
  const [data, setLoadedData] = useState<AppData | null>(null); const [page, setPage] = useState<Page>('assets'); const [modal, setModal] = useState<ModalState>(null); const [toast, setToast] = useState('')
  useEffect(() => { loadData().then(setLoadedData) }, [])
  const setData = (fn: (current: AppData) => AppData) => { if (!data) return; const next = fn(data); setLoadedData(next); void saveData(next) }
  const message = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2800) }
  const updateRates = async () => { if (!data) return; message('正在获取法币与加密货币汇率…'); try { const [fiatResponse, cryptoResponse] = await Promise.all([fetch('https://open.er-api.com/v6/latest/USD'), fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,tether,usd-coin&vs_currencies=usd')]); const fiat = await fiatResponse.json() as { rates?: Record<string, number> }; const crypto = await cryptoResponse.json() as Record<string, { usd?: number }>; if (!fiatResponse.ok || !cryptoResponse.ok || !fiat.rates?.CNY || !crypto.bitcoin?.usd || !crypto.ethereum?.usd) throw new Error('rate unavailable'); const cryptoIds: Record<string, keyof typeof crypto> = { BTC: 'bitcoin', ETH: 'ethereum', USDT: 'tether', USDC: 'usd-coin' }; const now = new Date().toISOString(); setData(current => { const rates: Record<string, Rate> = {}; supportedCurrencies.forEach(([code]) => { const usdValue = code === 'USD' ? 1 : cryptoIds[code] ? crypto[cryptoIds[code]]?.usd : fiat.rates?.[code] ? 1 / fiat.rates[code] : undefined; if (usdValue && usdValue > 0) rates[code] = { currency: code, usdValue, updatedAt: now } }); return { ...current, rates, settings: { ...current.settings, lastRateUpdate: now } } }); message('法币与加密货币汇率已更新') } catch { message('未能更新汇率，请检查网络后重试') } }
  const importData = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const incoming = JSON.parse(String(reader.result)) as AppData; if (incoming.version !== 1 || !Array.isArray(incoming.accounts) || !Array.isArray(incoming.transactions) || !incoming.rates) throw new Error(); if (window.confirm('导入会替换当前手机上的全部数据，是否继续？')) { setLoadedData(incoming); void saveData(incoming); message('备份已恢复') } } catch { message('这不是有效的净值备份文件') } }; reader.readAsText(file) }
  if (!data) return <div className="loading"><span>◒</span><b>正在打开你的本地账本</b></div>
  const saveAccount = (account: Account) => { setData(current => ({ ...current, accounts: current.accounts.some(a => a.id === account.id) ? current.accounts.map(a => a.id === account.id ? account : a) : [...current.accounts, account] })); setModal(null); message('账户已保存') }
  const saveEntry = (entry: Transaction) => { setData(current => ({ ...current, transactions: current.transactions.some(t => t.id === entry.id) ? current.transactions.map(t => t.id === entry.id ? entry : t) : [...current.transactions, entry] })); setModal(null); message('流水已保存') }
  const removeEntry = (entry: Transaction) => { if (window.confirm('删除这笔记录？账户余额会立即重新计算。')) { setData(current => ({ ...current, transactions: current.transactions.filter(t => t.id !== entry.id) })); message('记录已删除') } }
  const deleteAccount = (account: Account) => { if (window.confirm(`删除“${account.name}”及其全部关联流水？此操作无法撤销。`)) { setData(current => removeAccount(current, account.id)); setModal(null); message('账户及关联流水已删除') } }
  return <div className="app-shell"><div className="app-content">{page === 'assets' && <AssetsPage data={data} openEntry={() => setModal({ kind: 'entry' })}/>} {page === 'accounts' && <AccountsPage data={data} setData={setData} openAccount={account => setModal({ kind: 'account', account })}/>} {page === 'bills' && <BillsPage data={data} openEntry={() => setModal({ kind: 'entry' })} editEntry={entry => setModal({ kind: 'entry', entry })} removeEntry={removeEntry}/>} {page === 'settings' && <SettingsPage data={data} setData={setData} updateRates={updateRates} importData={importData}/>}</div><nav className="tabbar">{([['assets', '◌', '资产'], ['accounts', '▤', '账户'], ['bills', '≡', '账单'], ['settings', '⚙', '设置']] as [Page, string, string][]).map(([key, icon, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => setPage(key)}><span>{icon}</span>{label}</button>)}</nav>{modal?.kind === 'account' && <AccountForm data={data} account={modal.account} onSave={saveAccount} onDelete={deleteAccount} onClose={() => setModal(null)}/>} {modal?.kind === 'entry' && <EntryForm data={data} entry={modal.entry} onSave={saveEntry} onClose={() => setModal(null)}/>} {toast && <div className="toast">{toast}</div>}</div>
}
